{% set name = "napari-brightness-contrast" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-brightness-contrast-{{ version }}.tar.gz
  sha256: 88e0db47817a487b0db2b426ccfea88a57cbbf0185bf3ee0770fba81ed205dda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - pyqtgraph
    - python >={{ python_min }}
    - superqt

test:
  imports:
    - napari_brightness_contrast
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-brightness-contrast
  summary: Advanced layer visualization options
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
